services:
  postgres:
    image: postgres:16-alpine
    container_name: ransomware_live_postgres
    environment:
      POSTGRES_DB: ransomware_live
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ransomware_live_event_victim
    depends_on:
      - postgres
    environment:
      MY_API_KEY: ${MY_API_KEY:-}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-ransomware_live}
      POSTGRES_MAINTENANCE_DB: ${POSTGRES_MAINTENANCE_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DATABASE_URL: ${DATABASE_URL:-}

volumes:
  postgres_data: